name: CrearImagen
on: 
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v3
          - name: Log in to Docker Hub
            uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
            with:
              username: eduaranaya94  #Pendiente crear el secreto
              password: dckr_pat_A5gS8cPbs-BZA2RJ1Zjj28XAYeA # Pendiente Crear el secreto
          - run: ls -lah docker/  
          - name: Build and push
            uses: docker/build-push-action@v5
            with:
              context: "docker/Dockerfile ."
              push: true
              tags: philadelpfia-phillips:latest
